# Generated by Django 3.1.7 on 2021-03-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='question_text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='notebook',
            name='plain_note',
            field=models.TextField(blank=True),
        ),
    ]
