# Generated by Django 3.1.7 on 2021-03-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_auto_20210315_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
