# Generated by Django 3.1.7 on 2021-03-19 01:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_notebook_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 1, 40, 36, 690996, tzinfo=utc), verbose_name='date Updated'),
        ),
    ]
